Fix install script

diff --git a/install_script b/install_script
--- a/install_script
+++ b/install_script
@@ -1,5 +1,13 @@
 # Installs just_wrapper plugin for Oh My Zsh
 
+# $ZSH_CUSTOM is passed as an arg to this script since it is not available in the environment
+if [ -z "$1" ]; then
+    echo "Error: ZSH_CUSTOM directory not provided"
+    exit 1
+fi
+
+ZSH_CUSTOM=$1
+
 DOWNLOAD_LOCATION="https://github.com/swils23/just_wrapper/archive/main.zip"
 JW_PLUGIN_DIR="$ZSH_CUSTOM/plugins/just_wrapper/"
 
@@ -13,12 +21,16 @@ curl -LOks $DOWNLOAD_LOCATION -o main.zip
 unzip main.zip
 rm main.zip
 
-# Move the plugin to the custom plugins directory
+
 if [ -d "$JW_PLUGIN_DIR" ]; then
     echo "Directory $JW_PLUGIN_DIR already exists. Updating..."
     rm -rf "$JW_PLUGIN_DIR"
+else
+    echo "Installing just_wrapper plugin..."
 fi
-mv just_wrapper-main/just_wrapper "$JW_PLUGIN_DIR"
+mkdir -p "$JW_PLUGIN_DIR"
+# mv just_wrapper-main/just_wrapper "$JW_PLUGIN_DIR"
+cp -r just_wrapper-main/just_wrapper "$JW_PLUGIN_DIR"
 
 # Post-installation cleanup
 cd $current_dir
